/**
 * Display query expansions generated by multi-query expansion.
 */

import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Copy, Lightbulb } from "lucide-react";

interface QueryExpansionsPanelProps {
  originalQuery: string;
  expansions: string[];
}

export function QueryExpansionsPanel({
  originalQuery,
  expansions,
}: QueryExpansionsPanelProps) {
  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
  };

  return (
    <Card className="p-6 space-y-4">
      <div className="flex items-center gap-2">
        <Lightbulb className="w-5 h-5 text-yellow-600" />
        <h3 className="font-semibold text-lg">Query Expansions</h3>
      </div>

      <div className="space-y-3">
        {/* Original query */}
        <div className="p-3 rounded-lg bg-blue-50 border border-blue-200">
          <div className="flex items-start justify-between gap-2 mb-2">
            <Badge variant="secondary" className="bg-blue-100 text-blue-700">
              Original Query
            </Badge>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => copyToClipboard(originalQuery)}
            >
              <Copy className="w-3 h-3" />
            </Button>
          </div>
          <p className="text-sm text-blue-900 font-medium">{originalQuery}</p>
        </div>

        {/* Expanded queries */}
        {expansions.length > 0 ? (
          expansions.map((expansion, idx) => (
            <div
              key={idx}
              className="p-3 rounded-lg bg-purple-50 border border-purple-200"
            >
              <div className="flex items-start justify-between gap-2 mb-2">
                <Badge
                  variant="secondary"
                  className="bg-purple-100 text-purple-700"
                >
                  Expansion {idx + 1}
                </Badge>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => copyToClipboard(expansion)}
                >
                  <Copy className="w-3 h-3" />
                </Button>
              </div>
              <p className="text-sm text-purple-900">{expansion}</p>
            </div>
          ))
        ) : (
          <div className="p-3 rounded-lg bg-gray-50 border border-gray-200">
            <p className="text-sm text-gray-500">
              No expansions generated. Using original query only.
            </p>
          </div>
        )}
      </div>

      <div className="pt-2 border-t border-gray-200">
        <p className="text-xs text-gray-500">
          Multi-query expansion helps retrieve chunks from multiple angles of
          understanding. Each query targets different aspects of the concept.
        </p>
      </div>
    </Card>
  );
}
